---
- name: Install default Ubuntu Apache
  hosts: ubuntu
  become: yes

  tasks:
          - name: Install Apache WebServer on Ubuntu
            apt: name=apache2 state=latest

          - name: State Apache and Enable it on the every boot
            service: name=apache2 state=started enabled=yes

- name: Install CentOS aoache
  hosts: centos
  become: yes

  tasks:
          - name: Install Apache WebServer on CentOS
            yum: name=httpd state=latest
            shell: 

          - name: State Apache and Enable it on the every boot
            service: name=httpd state=started enabled=yes

