---

- name: Install default zabbix-agent
  hosts: ubuntu.my 
  become: yes

  vars:
          source_file_ubuntu: /etc/ansible/common/files/zabbix/agent/ubuntu/zabbix_agentd.conf
          dest_file: /etc/zabbix/zabbix_agentd.conf

  tasks:
          - name: Install zabbix-agent on ubuntu servers
            apt: name=zabbix-agent state=latest

          - name: Copy config file for ubuntu.my
            copy: src={{ source_file_ubuntu }} dest={{ dest_file }} mode=0644
            notify: Restart agent

          - name: State Zabbix and Enable it on the every boot
            service: name=zabbix-agent state=started enabled=yes

  handlers: 
          - name: Restart agent
            service: name=zabbix-agent state=restarted

- name: Install default zabbix-agent
  hosts: centos
  become: yes
  vars:
          source_file_centos: /etc/ansible/common/files/zabbix/agent/centos/zabbix_agentd.conf
          dest_file: /etc/zabbix/zabbix_agentd.conf

  tasks:
          - name: Install zabbix-agent on CentOS servers
            yum: name=zabbix-agent state=latest
            
          - name: Copy config file for centos
            copy: src={{ source_file_centos }} dest={{ dest_file }} mode=0644
            notify: Restart agent
            
          - name: State Zabbix and Enable it on the every boot
            service: name=zabbix-agent state=started enabled=yes
  handlers:
          - name: Restart agent
            service: name=zabbix-agent state=restarted
